In [114]:
import pandas as pd

# Cargar los datos
df = pd.read_csv('datos.csv', header = 0)

# Convertir fechas
df['Fecha'] = pd.to_datetime(df['Fecha'], dayfirst=True)

df

,Semana,Fecha,11,1,12,2,13,3,14,4,...,16,6,17,7,18,8,19,9,20,10
0,NaN,NaT,Dato demanda,Dato precio,Dato demanda,Dato precio,Dato demanda,Dato precio,Dato demanda,Dato precio,...,Dato demanda,Dato precio,Dato demanda,Dato precio,Dato demanda,Dato precio,Dato demanda,Dato precio,Dato demanda,Dato precio
1,1.0,2021-01-01,2319,28.79,5683,18.39,3153,30.39,947,55.99,...,2701,49.59,5361,68.79,2122,49.59,1585,31.99,4326,17.59
2,2.0,2021-01-08,3180,28.79,1875,18.39,4543,30.39,651,55.99,...,1573,49.59,2151,68.79,3990,49.59,4682,31.99,8585,17.59
3,3.0,2021-01-15,1856,35.99,7368,22.99,3076,37.99,1555,69.99,...,2005,61.99,6204,85.99,1907,61.99,2329,39.99,8827,21.99
4,4.0,2021-01-22,3295,35.99,5414,22.99,3674,37.99,1210,69.99,...,3055,61.99,5690,85.99,3969,61.99,2945,39.99,7799,21.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,214.0,2025-01-31,2366,35.99,11341,22.99,3076,37.99,994,69.99,...,2245,61.99,5665,85.99,2796,61.99,3894,39.99,9537,21.99
215,215.0,2025-02-07,1556,28.79,6137,18.39,2161,30.39,994,55.99,...,1391,49.59,5886,68.79,2918,49.59,3098,31.99,5918,17.59
216,216.0,2025-02-14,1628,28.79,5417,18.39,2674,30.39,994,55.99,...,2853,49.59,3688,68.79,3320,49.59,3359,31.99,9028,17.59
217,217.0,2025-02-21,3290,28.79,7273,18.39,4555,30.39,994,55.99,...,2108,49.59,2734,68.79,2357,49.59,1797,31.99,13435,17.59
218,218.0,2025-02-28,2040,35.99,7486,22.99,3783,37.99,994,69.99,...,2365,61.99,8665,85.99,2865,61.99,5857,39.99,9285,21.99

In [115]:
#funcion que extrae los datos del producto n con n del 1 al 10

def extraer_datos_producto(df, n):
    # Filtrar el DataFrame para obtener solo los datos del producto n dejo columnas Semana, Fecha, n y n+10

    columnas_n = ['Semana', 'Fecha', f'{n+10}', f'{n}']
    df_producto = df[columnas_n]
    
    # Renombrar las columnas para que sean mÃ¡s descriptivas
    df_producto.columns = ['Semana', 'Fecha', 'Demanda', 'Precio']

    #Agregar mes, dÃ­a y aÃ±o

    df_producto['Mes'] = df_producto['Fecha'].dt.month
    df_producto['Dia'] = df_producto['Fecha'].dt.day
    df_producto['AÃ±o'] = df_producto['Fecha'].dt.year

    #drop fila 0
    df_producto = df_producto.drop(index=0)

    df_producto['Semana del AÃ±o'] = df_producto['Fecha'].dt.isocalendar().week

    #drop fecha
    df_producto = df_producto.drop(columns=['Fecha'])


    return df_producto


df_producto_1 = extraer_datos_producto(df, 1)
df_producto_1

C:\Users\itzae\AppData\Local\Temp\ipykernel_12904\2501719728.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_producto['Mes'] = df_producto['Fecha'].dt.month
C:\Users\itzae\AppData\Local\Temp\ipykernel_12904\2501719728.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_producto['Dia'] = df_producto['Fecha'].dt.day
C:\Users\itzae\AppData\Local\Temp\ipykernel_12904\2501719728.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_producto['AÃ±o'] = df_producto['Fecha'].dt.year

     Semana Demanda Precio  Mes   Dia     AÃ±o  Semana del AÃ±o
1       1.0    2319  28.79  1.0   1.0  2021.0              53
2       2.0    3180  28.79  1.0   8.0  2021.0               1
3       3.0    1856  35.99  1.0  15.0  2021.0               2
4       4.0    3295  35.99  1.0  22.0  2021.0               3
5       5.0    2375  35.99  1.0  29.0  2021.0               4
..      ...     ...    ...  ...   ...     ...             ...
214   214.0    2366  35.99  1.0  31.0  2025.0               5
215   215.0    1556  28.79  2.0   7.0  2025.0               6
216   216.0    1628  28.79  2.0  14.0  2025.0               7
217   217.0    3290  28.79  2.0  21.0  2025.0               8
218   218.0    2040  35.99  2.0  28.0  2025.0               9

[218 rows x 7 columns]

In [116]:
#importar df de demanda de ropa

df_demanda_ropa = pd.read_csv('demanda_ropa_chile.csv', header = 0, sep=';')

df_demanda_ropa

    Semana Demanda_Ropa  Demanda Ropa
0        1         baja             1
1        2         baja             1
2        3         baja             1
3        4         baja             1
4        5         baja             1
5        6         baja             1
6        7         baja             1
7        8         baja             1
8        9         alta             1
9       10         alta             1
10      11        media             2
11      12         alta             3
12      13         alta             3
13      14         alta             3
14      15         alta             3
15      16         alta             3
16      17         alta             3
17      18     muy alta             4
18      19     muy alta             4
19      20        media             2
20      21        media             2
21      22     muy alta             4
22      23        media             2
23      24         alta             3
24      25         alta             3
25      26        media             2
26      27        media             2
27      28        media             2
28      29        media             2
29      30        media             2
30      31        media             2
31      32        media             2
32      33        media             2
33      34        media             2
34      35        media             2
35      36        media             2
36      37         alta             3
37      38         alta             3
38      39        media             2
39      40         alta             3
40      41         alta             3
41      42         alta             3
42      43        media             2
43      44     muy alta             4
44      45        media             2
45      46        media             2
46      47     muy alta             4
47      48     muy alta             4
48      49        media             2
49      50     muy alta             4
50      51     muy alta             4
51      52     muy alta             4

In [117]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler

df_producto_1

     Semana Demanda Precio  Mes   Dia     AÃ±o  Semana del AÃ±o
1       1.0    2319  28.79  1.0   1.0  2021.0              53
2       2.0    3180  28.79  1.0   8.0  2021.0               1
3       3.0    1856  35.99  1.0  15.0  2021.0               2
4       4.0    3295  35.99  1.0  22.0  2021.0               3
5       5.0    2375  35.99  1.0  29.0  2021.0               4
..      ...     ...    ...  ...   ...     ...             ...
214   214.0    2366  35.99  1.0  31.0  2025.0               5
215   215.0    1556  28.79  2.0   7.0  2025.0               6
216   216.0    1628  28.79  2.0  14.0  2025.0               7
217   217.0    3290  28.79  2.0  21.0  2025.0               8
218   218.0    2040  35.99  2.0  28.0  2025.0               9

[218 rows x 7 columns]

In [118]:
df_producto_1 = df_producto_1.dropna(subset=['Demanda'])
#hacer numericos los datos de demanda
df_producto_1['Demanda'] = pd.to_numeric(df_producto_1['Demanda'], errors='coerce')

# Dividir en 5 categorÃ­as
#df_producto_1['Categoria Demanda'] = pd.qcut(df_producto_1['Demanda'], q=5, labels=[0, 1, 2, 3, 4])



#drop demanda

#df_producto_1 = df_producto_1.drop(columns=['Demanda'])

df_producto_1

     Semana  Demanda Precio  Mes   Dia     AÃ±o  Semana del AÃ±o
1       1.0     2319  28.79  1.0   1.0  2021.0              53
2       2.0     3180  28.79  1.0   8.0  2021.0               1
3       3.0     1856  35.99  1.0  15.0  2021.0               2
4       4.0     3295  35.99  1.0  22.0  2021.0               3
5       5.0     2375  35.99  1.0  29.0  2021.0               4
..      ...      ...    ...  ...   ...     ...             ...
214   214.0     2366  35.99  1.0  31.0  2025.0               5
215   215.0     1556  28.79  2.0   7.0  2025.0               6
216   216.0     1628  28.79  2.0  14.0  2025.0               7
217   217.0     3290  28.79  2.0  21.0  2025.0               8
218   218.0     2040  35.99  2.0  28.0  2025.0               9

[218 rows x 7 columns]

In [119]:

#drop semana

df_producto_1 = df_producto_1.drop(columns=['Semana'])

In [120]:
#del df_demanda_ropa quiero agregar la columna Categoria Demanda al df_producto_1 si es que def_demanda_ropa['Semana'] == df_producto_1['Semana del AÃ±o']

df_producto_1 = df_producto_1.merge(df_demanda_ropa[['Semana', 'Demanda Ropa']], left_on='Semana del AÃ±o', right_on='Semana', how='left')

In [121]:
#drop na en semana y demanda ropa

df_producto_1 = df_producto_1.dropna(subset=['Semana del AÃ±o', 'Demanda Ropa'])

In [122]:


df_producto_1.drop(columns=['Semana'], inplace=True)

In [127]:
df_producto_1

#precio es el precio del producto
#mes dia y aÃ±o es la fecha de la semana estudiada
#demanda ropa es la demanda de ropa en la semana estudiada
#categoria demanda es la categoria de la demanda del producto
#semana del aÃ±o es la semana del aÃ±o de la fecha estudiada, del 1 al 52

     Demanda Precio  Mes   Dia     AÃ±o  Semana del AÃ±o  Demanda Ropa
1       3180  28.79  1.0   8.0  2021.0               1           1.0
2       1856  35.99  1.0  15.0  2021.0               2           1.0
3       3295  35.99  1.0  22.0  2021.0               3           1.0
4       2375  35.99  1.0  29.0  2021.0               4           1.0
5       1584  28.79  2.0   5.0  2021.0               5           1.0
..       ...    ...  ...   ...     ...             ...           ...
213     2366  35.99  1.0  31.0  2025.0               5           1.0
214     1556  28.79  2.0   7.0  2025.0               6           1.0
215     1628  28.79  2.0  14.0  2025.0               7           1.0
216     3290  28.79  2.0  21.0  2025.0               8           1.0
217     2040  35.99  2.0  28.0  2025.0               9           1.0

[217 rows x 7 columns]

In [124]:
#prediccion de un df con la forma Semana, Demanda, Precio, Mes, Dia, AÃ±o
from sklearn.metrics import classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

#divdir train test

X = df_producto_1[['Precio', 'Mes', 'Dia', 'AÃ±o', 'Semana del AÃ±o', 'Demanda Ropa']]
y = df_producto_1['Categoria Demanda']

#normalizar x
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crear el modelo de xbclassifier
from xgboost import XGBClassifier

model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
model.fit(X_train, y_train)
# Hacer predicciones
y_pred = model.predict(X_test)
# Calcular el error cuadrÃ¡tico medio
mse = mean_squared_error(y_test, y_pred)
print("Error cuadrÃ¡tico medio:", mse)
# Calcular el coeficiente de determinaciÃ³n R^2
r2 = r2_score(y_test, y_pred)
print("Coeficiente de determinaciÃ³n R^2:", r2)

KeyError: 'Categoria Demanda'

In [ ]:
#usar xgboost

import xgboost as xgb

# Crear el modelo de XGBoost
model_xgb = xgb.XGBRegressor(n_estimators=100, random_state=42)
# Entrenar el modelo
model_xgb.fit(X_train, y_train)
# Realizar predicciones
y_pred_xgb = model_xgb.predict(X_test)
# EvaluaciÃ³n
mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
mse_xgb = mean_squared_error(y_test, y_pred_xgb)
rmse_xgb = np.sqrt(mse_xgb)

r2_xgb = r2_score(y_test, y_pred_xgb)
print(f"MAE XGBoost: {mae_xgb:.2f}")
print(f"MSE XGBoost: {mse_xgb:.2f}")
print(f"RMSE XGBoost: {rmse_xgb:.2f}")
print(f"RÂ² Score XGBoost: {r2_xgb:.3f}")
#prediccion de un df con la forma Semana, Demanda, Precio, Mes, Dia, AÃ±o
# Crear un nuevo DataFrame para la predicciÃ³n

MAE XGBoost: 0.34
MSE XGBoost: 0.20
RMSE XGBoost: 0.45
RÂ² Score XGBoost: -0.474

Ahora probamos con clusters de demanda

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import Pipeline

# Usamos el DataFrame que ya tienes cargado: df_producto_1

# 1. ExploraciÃ³n de datos
print("InformaciÃ³n del DataFrame:")
print(df_producto_1.info())
print("\nEstadÃ­sticas descriptivas:")
print(df_producto_1.describe())
print("\nPrimeras filas del DataFrame:")
print(df_producto_1.head())

# Verificar valores nulos
print("\nValores nulos por columna:")
print(df_producto_1.isnull().sum())

# Visualizar la distribuciÃ³n de la variable objetivo
plt.figure(figsize=(10, 6))
sns.countplot(x='Categoria Demanda', data=df_producto_1)
plt.title('DistribuciÃ³n de CategorÃ­a de Demanda')
plt.xticks(rotation=0)
plt.savefig('distribucion_categoria_demanda.png')
plt.close()

# 2. PreparaciÃ³n de datos
# Dividimos los datos en caracterÃ­sticas (X) y variable objetivo (y)
X = df_producto_1[['Precio', 'Mes', 'Dia', 'AÃ±o', 'Semana del AÃ±o', 'Demanda Ropa']]
y = df_producto_1['Categoria Demanda']

# Dividimos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nTamaÃ±o del conjunto de entrenamiento: {X_train.shape}")
print(f"TamaÃ±o del conjunto de prueba: {X_test.shape}")

# 3. CreaciÃ³n y entrenamiento del modelo
# Definimos un pipeline con escalado de caracterÃ­sticas y el modelo Random Forest
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('random_forest', RandomForestClassifier(random_state=42))
])

# Definimos una cuadrÃ­cula de hiperparÃ¡metros para buscar los mejores
param_grid = {
    'random_forest__n_estimators': [50, 100, 200],
    'random_forest__max_depth': [None, 10, 20, 30],
    'random_forest__min_samples_split': [2, 5, 10],
    'random_forest__min_samples_leaf': [1, 2, 4]
}

# BÃºsqueda de los mejores hiperparÃ¡metros con validaciÃ³n cruzada
print("\nIniciando bÃºsqueda de hiperparÃ¡metros...")
grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Obtenemos el mejor modelo
best_model = grid_search.best_estimator_
print(f"\nMejores hiperparÃ¡metros encontrados: {grid_search.best_params_}")

# 4. EvaluaciÃ³n del modelo
# Hacemos predicciones en el conjunto de prueba
y_pred = best_model.predict(X_test)

# Evaluamos el rendimiento del modelo
print("\nInforme de clasificaciÃ³n:")
print(classification_report(y_test, y_pred))

# Matriz de confusiÃ³n
plt.figure(figsize=(10, 8))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
            xticklabels=sorted(y.unique()), 
            yticklabels=sorted(y.unique()))
plt.xlabel('PredicciÃ³n')
plt.ylabel('Valor Real')
plt.title('Matriz de ConfusiÃ³n')
plt.savefig('matriz_confusion.png')
plt.close()

# 5. Importancia de caracterÃ­sticas
if hasattr(best_model[-1], 'feature_importances_'):
    # Obtenemos la importancia de las caracterÃ­sticas
    importances = best_model[-1].feature_importances_
    feature_names = X.columns
    
    # Ordenamos las caracterÃ­sticas por importancia
    indices = np.argsort(importances)[::-1]
    
    # Visualizamos la importancia de las caracterÃ­sticas
    plt.figure(figsize=(10, 6))
    plt.title('Importancia de las CaracterÃ­sticas')
    plt.bar(range(X.shape[1]), importances[indices], align='center')
    plt.xticks(range(X.shape[1]), [feature_names[i] for i in indices], rotation=90)
    plt.tight_layout()
    plt.savefig('importancia_caracteristicas.png')
    plt.close()
    
    print("\nImportancia de caracterÃ­sticas:")
    for i in indices:
        print(f"{feature_names[i]}: {importances[i]:.4f}")

# 6. Guardamos el modelo para uso futuro
import joblib
joblib.dump(best_model, 'modelo_random_forest_demanda.pkl')
print("\nModelo guardado como 'modelo_random_forest_demanda.pkl'")

# 7. Ejemplo de cÃ³mo usar el modelo para hacer predicciones
# Supongamos que queremos predecir la categorÃ­a de demanda para una nueva semana
# IMPORTANTE: Usamos exactamente los mismos nombres de columnas que en el entrenamiento
nuevo_dato = pd.DataFrame({
    'Precio': [28.79],
    'Mes': [3.0],
    'Dia': [15.0],
    'AÃ±o': [2025.0],
    'Semana del AÃ±o': [12],  # Corregido: Espacio en lugar de guion bajo
    'Demanda Ropa': [1.0]    # Corregido: Espacio en lugar de guion bajo
})

# Hacemos la predicciÃ³n
prediccion = best_model.predict(nuevo_dato)
print(f"\nPredicciÃ³n para el nuevo dato: CategorÃ­a de Demanda {prediccion[0]}")

# 8. FunciÃ³n para realizar predicciones
def predecir_categoria_demanda(precio, mes, dia, anio, semana_anio, demanda_ropa):
    """
    FunciÃ³n para predecir la categorÃ­a de demanda usando el modelo entrenado
    """
    datos = pd.DataFrame({
        'Precio': [precio],
        'Mes': [mes],
        'Dia': [dia],
        'AÃ±o': [anio],
        'Semana del AÃ±o': [semana_anio],  # Corregido: Espacio en lugar de guion bajo
        'Demanda Ropa': [demanda_ropa]    # Corregido: Espacio en lugar de guion bajo
    })
    
    return best_model.predict(datos)[0]

# Ejemplo de uso de la funciÃ³n
print("\nEjemplo de uso de la funciÃ³n de predicciÃ³n:")
categoria_predicha = predecir_categoria_demanda(35.99, 4.0, 20.0, 2025.0, 16, 1.0)
print(f"CategorÃ­a de Demanda predicha: {categoria_predicha}")

InformaciÃ³n del DataFrame:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 217 entries, 1 to 217
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Precio             217 non-null    object
 1   Mes                217 non-null    float64
 2   Dia                217 non-null    float64
 3   AÃ±o                217 non-null    float64
 4   Semana del AÃ±o     217 non-null    UInt32
 5   Categoria Demanda  217 non-null    category
 6   Demanda Ropa       217 non-null    float64
dtypes: UInt32(1), category(1), float64(4), object(1)
memory usage: 11.7+ KB
None

EstadÃ­sticas descriptivas:
              Mes         Dia          AÃ±o  Semana del AÃ±o  Demanda Ropa
count  217.000000  217.000000   217.000000           217.0    217.000000
mean     6.373272   15.737327  2022.603687       25.608295      2.345622
std      3.532105    8.808673     1.205537       15.350791      1.007101
min      1.000000    1.000000  2021.000000             1.0      1.000000
25%      3.000000    8.000000  2022.000000            12.0      2.000000
50%      6.000000   16.000000  2023.000000            25.0      2.000000
75%      9.000000   23.000000  2024.000000            39.0      3.000000
max     12.000000   31.000000  2025.000000            52.0      4.000000

Primeras filas del DataFrame:
  Precio  Mes   Dia     AÃ±o  Semana del AÃ±o Categoria Demanda  Demanda Ropa
1  28.79  1.0   8.0  2021.0               1                 3           1.0
2  35.99  1.0  15.0  2021.0               2                 0           1.0
3  35.99  1.0  22.0  2021.0               3                 3           1.0
4  35.99  1.0  29.0  2021.0               4                 1           1.0
5  28.79  2.0   5.0  2021.0               5                 0           1.0

Valores nulos por columna:
Precio               0
Mes                  0
Dia                  0
AÃ±o                  0
Semana del AÃ±o       0
Categoria Demanda    0
Demanda Ropa         0
dtype: int64

TamaÃ±o del conjunto de entrenamiento: (173, 6)
TamaÃ±o del conjunto de prueba: (44, 6)

Iniciando bÃºsqueda de hiperparÃ¡metros...

Mejores hiperparÃ¡metros encontrados: {'random_forest__max_depth': None, 'random_forest__min_samples_leaf': 1, 'random_forest__min_samples_split': 2, 'random_forest__n_estimators': 50}

Informe de clasificaciÃ³n:
              precision    recall  f1-score   support

           0       0.50      0.20      0.29        10
           1       0.33      0.29      0.31         7
           2       0.17      0.20      0.18        10
           3       0.08      0.17      0.11         6
           4       0.10      0.09      0.10        11

    accuracy                           0.18        44
   macro avg       0.24      0.19      0.20        44
weighted avg       0.24      0.18      0.19        44


Importancia de caracterÃ­sticas:
Dia: 0.3207
Semana del AÃ±o: 0.2293
AÃ±o: 0.1990
Mes: 0.1155
Precio: 0.0728
Demanda Ropa: 0.0628

Modelo guardado como 'modelo_random_forest_demanda.pkl'

PredicciÃ³n para el nuevo dato: CategorÃ­a de Demanda 0

Ejemplo de uso de la funciÃ³n de predicciÃ³n:
CategorÃ­a de Demanda predicha: 0

In [ ]:
#classification report

print(classification_report(y_test, y_pred))
#confusion matrix
confusion_matrix(y_test, y_pred)
#accuracy
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.20      0.29        10
           1       0.33      0.29      0.31         7
           2       0.17      0.20      0.18        10
           3       0.08      0.17      0.11         6
           4       0.10      0.09      0.10        11

    accuracy                           0.18        44
   macro avg       0.24      0.19      0.20        44
weighted avg       0.24      0.18      0.19        44

0.18181818181818182

In [ ]:
pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\users\itzae\appdata\local\programs\python\python310\lib\site-packages (from lightgbm) (1.23.5)
Requirement already satisfied: scipy in c:\users\itzae\appdata\local\programs\python\python310\lib\site-packages (from lightgbm) (1.14.1)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 1.5/1.5 MB 19.2 MB/s eta 0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# DefiniciÃ³n de la funciÃ³n para entrenar y comparar los modelos
def entrenar_comparar_modelos(X, y, test_size=0.2, random_state=42):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
    
    # Preprocesamiento
    numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
    preprocessor = Pipeline([('scaler', StandardScaler())])

    # Modelos a comparar
    modelos = {
        'Random Forest': RandomForestClassifier(random_state=random_state),
        'Gradient Boosting': GradientBoostingClassifier(random_state=random_state),
        'SVM': SVC(random_state=random_state),
        'KNN': KNeighborsClassifier(),
        'Logistic Regression': LogisticRegression(max_iter=1000, random_state=random_state),
    }
    
    resultados = {}
    for nombre, modelo in modelos.items():
        pipeline = Pipeline([('preprocessor', preprocessor), ('classifier', modelo)])
        pipeline.fit(X_train, y_train)
        
        y_pred = pipeline.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        
        # ValidaciÃ³n cruzada
        cv_scores = cross_val_score(pipeline, X, y, cv=5, scoring='accuracy')
        
        resultados[nombre] = {
            'accuracy': accuracy,
            'cv_accuracy_mean': cv_scores.mean(),
            'cv_accuracy_std': cv_scores.std()
        }
        print(f"{nombre} - Accuracy: {accuracy:.4f}, CV Accuracy: {cv_scores.mean():.4f} Â± {cv_scores.std():.4f}")

    # Graficar resultados
    comparar_modelos_grafico(resultados)
    
    return resultados

# FunciÃ³n para graficar la comparaciÃ³n de modelos
def comparar_modelos_grafico(resultados):
    nombres = list(resultados.keys())
    accuracies = [info['accuracy'] for info in resultados.values()]
    cv_accuracies = [info['cv_accuracy_mean'] for info in resultados.values()]
    
    plt.figure(figsize=(12, 6))
    x = np.arange(len(nombres))
    width = 0.35
    
    plt.bar(x - width/2, accuracies, width, label='Test Accuracy')
    plt.bar(x + width/2, cv_accuracies, width, label='CV Accuracy')
    
    plt.xlabel('Modelo')
    plt.ylabel('PrecisiÃ³n')
    plt.title('ComparaciÃ³n de Modelos de ClasificaciÃ³n')
    plt.xticks(x, nombres, rotation=45, ha='right')
    plt.ylim(0, 1.0)
    plt.legend()
    plt.tight_layout()
    
    # Guardar grÃ¡fico
    plt.savefig('comparacion_modelos.png')
    plt.close()

# Uso de la funciÃ³n
# SupÃ³n que tienes tus datos en las variables X y y
# resultados = entrenar_comparar_modelos(X, y)

In [ ]:
entrenar_comparar_modelos(X, y)

Random Forest - Accuracy: 0.1818, CV Accuracy: 0.2072 Â± 0.0405
Gradient Boosting - Accuracy: 0.1364, CV Accuracy: 0.2027 Â± 0.0170
SVM - Accuracy: 0.2045, CV Accuracy: 0.2395 Â± 0.0167
KNN - Accuracy: 0.1364, CV Accuracy: 0.1798 Â± 0.0275
Logistic Regression - Accuracy: 0.3409, CV Accuracy: 0.2585 Â± 0.0513

{'Random Forest': {'accuracy': 0.18181818181818182,
  'cv_accuracy_mean': 0.20718816067653276,
  'cv_accuracy_std': 0.04048501590618581},
 'Gradient Boosting': {'accuracy': 0.13636363636363635,
  'cv_accuracy_mean': 0.20274841437632132,
  'cv_accuracy_std': 0.017046908996078827},
 'SVM': {'accuracy': 0.20454545454545456,
  'cv_accuracy_mean': 0.2395348837209302,
  'cv_accuracy_std': 0.016721961888613263},
 'KNN': {'accuracy': 0.13636363636363635,
  'cv_accuracy_mean': 0.1798097251585624,
  'cv_accuracy_std': 0.027549929399644586},
 'Logistic Regression': {'accuracy': 0.3409090909090909,
  'cv_accuracy_mean': 0.2584566596194503,
  'cv_accuracy_std': 0.05127013358044451}}

In [128]:
df_producto_1.head(20)

    Demanda Precio  Mes   Dia     AÃ±o  Semana del AÃ±o  Demanda Ropa
1      3180  28.79  1.0   8.0  2021.0               1           1.0
2      1856  35.99  1.0  15.0  2021.0               2           1.0
3      3295  35.99  1.0  22.0  2021.0               3           1.0
4      2375  35.99  1.0  29.0  2021.0               4           1.0
5      1584  28.79  2.0   5.0  2021.0               5           1.0
6      1538  28.79  2.0  12.0  2021.0               6           1.0
7      2296  28.79  2.0  19.0  2021.0               7           1.0
8      2177  35.99  2.0  26.0  2021.0               8           1.0
9      2334  35.99  3.0   5.0  2021.0               9           1.0
10     2534  39.59  3.0  12.0  2021.0              10           1.0
11     3648  43.19  3.0  19.0  2021.0              11           2.0
12     3536  43.19  3.0  26.0  2021.0              12           3.0
13     2529  43.19  4.0   2.0  2021.0              13           3.0
14     3181  43.19  4.0   9.0  2021.0              14           3.0
15     3264  43.19  4.0  16.0  2021.0              15           3.0
16     3791  43.19  4.0  23.0  2021.0              16           3.0
17     2330  43.19  4.0  30.0  2021.0              17           3.0
18     3973  43.19  5.0   7.0  2021.0              18           4.0
19     3295  43.19  5.0  14.0  2021.0              19           4.0
20     5329  43.19  5.0  21.0  2021.0              20           2.0

In [131]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error

# AsegÃºrate de que df_producto_1 estÃ© cargado
# X es el DataFrame con las caracterÃ­sticas (todas las columnas excepto 'Demanda')
# y es la variable objetivo 'Demanda'

X = df_producto_1.drop(columns=['Demanda'])
y = df_producto_1['Demanda']

# Dividir los datos en conjunto de entrenamiento y prueba (80% entrenamiento, 20% prueba)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocesamiento: escalar las caracterÃ­sticas numÃ©ricas
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
preprocessor = Pipeline([('scaler', StandardScaler())])

# Modelos a comparar
modelos = {
    'Random Forest': RandomForestRegressor(random_state=42),
    'Gradient Boosting': GradientBoostingRegressor(random_state=42),
    'SVM': SVR(),
    'KNN': KNeighborsRegressor(),
    'Linear Regression': LinearRegression(),
}

resultados = {}

for nombre, modelo in modelos.items():
    # Crear un pipeline con preprocesamiento y el modelo de regresiÃ³n
    pipeline = Pipeline([('preprocessor', preprocessor), ('regressor', modelo)])
    
    # Entrenar el modelo
    pipeline.fit(X_train, y_train)
    
    # Predecir en el conjunto de prueba
    y_pred = pipeline.predict(X_test)
    
    # Calcular las mÃ©tricas de error
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    
    # Guardar los resultados
    resultados[nombre] = {
        'MAE': mae,
        'RMSE': rmse,
    }

# Mostrar los resultados
for modelo, metrica in resultados.items():
    print(f"{modelo} - MAE: {metrica['MAE']:.4f}, RMSE: {metrica['RMSE']:.4f}")

#r2
for modelo, metrica in resultados.items():
    y_pred = pipeline.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    print(f"{modelo} - RÂ²: {r2:.4f}")

Random Forest - MAE: 712.1470, RMSE: 925.0748
Gradient Boosting - MAE: 803.5366, RMSE: 1031.9747
SVM - MAE: 739.5906, RMSE: 912.1710
KNN - MAE: 755.7318, RMSE: 945.9608
Linear Regression - MAE: 687.2337, RMSE: 866.5921
Random Forest - RÂ²: 0.0905
Gradient Boosting - RÂ²: 0.0905
SVM - RÂ²: 0.0905
KNN - RÂ²: 0.0905
Linear Regression - RÂ²: 0.0905